queue_rules:
  - name: dependabot-updates
    conditions:
      - check-success=Run Tests
      - check-success=Check Javadocs
      - check-success=Analyze
      - check-success=CodeQL
      - check-success=CodeFactor

pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions: [ 'author=dependabot[bot]' ]
    actions:
      queue:
        method: merge
        name: dependabot-updates
