name: Deploy snapshot

on:
  push:
    branches: [ development ]

jobs:
  deploy-snapshot:
    name: Deploy Snapshot
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Java 17 & Deployment credentials
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'
          server-id: 'sonatype-ossrh'
          server-username: SONATYPE_OSSRH_DEPLOYER
          server-password: SONATYPE_OSSRH_TOKEN
          gpg-private-key: ${{ secrets.CODE_SIGNING_GPG_PRIVATE_KEY }}
          gpg-passphrase: CODE_SIGNING_GPG_KEY_PASSPHRASE

      - uses: jactions/maven-version@v1.0.0
        id: get_version

      - name: Deploy snapshot
        if: ${{ endsWith(steps.get_version.outputs.version, '-SNAPSHOT') }}
        run: mvn deploy -B -P build-extras,sign-artifacts
        env:
          SONATYPE_OSSRH_DEPLOYER: ${{ secrets.SONATYPE_OSSRH_DEPLOYER }}
          SONATYPE_OSSRH_TOKEN: ${{ secrets.SONATYPE_OSSRH_TOKEN }}
          CODE_SIGNING_GPG_KEY_PASSPHRASE: ${{ secrets.CODE_SIGNING_GPG_KEY_PASSPHRASE }}
