name: Test

on: [ pull_request ]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.4.0

      - name: Set up Java 17
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'

      - name: Run tests
        # note: `package` is used instead of `test` in order to support MultiReleaseJar
        run: mvn -B package

  check-javadocs:
    name: Check Javadocs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.4.0

      - name: Set up Java 17
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'

      - name: Install artifacts
        run: mvn -B install -Dmaven.test.skip=true

      - name: Try to generate Javadocs
        run: mvn -B javadoc:javadoc
